seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

chromedebug1:
  image: selenium/node-chrome
  ports:
    - 4577
  links:
  - seleniumhub:hub

chromedebug2:
  image: selenium/node-chrome
  ports:
    - 4578
  links:
  - seleniumhub:hub